name: cipher_solver
description: A Flutter application for solving and creating ciphers
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

fonts:
  - family: MarkerFont
    fonts:
      - asset: assets/fonts/PermanentMarker-Regular.ttf

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_services_binding: ^0.1.0
  pdf: ^3.10.4
  printing: ^5.10.4
  google_fonts: ^5.1.0
  #wheel_chooser: ^1.1.2 
  selector_wheel: ^1.1.2
  shared_preferences: ^2.2.0

  # Add these for the cipher application
  path_provider: ^2.0.15
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true
  
  # Uncomment and modify this section when you add cipher images
  assets:
    - assets/
    - assets/Runes/a/
    - assets/Runes/b/
    - assets/Runes/c/
    - assets/Runes/d/
    - assets/Runes/e/
    - assets/Runes/f/
    - assets/Runes/g/
    - assets/Runes/h/
    - assets/Runes/i/
    - assets/Runes/j/
    - assets/Runes/k/
    - assets/Runes/l/
    - assets/Runes/m/
    - assets/Runes/n/
    - assets/Runes/o/
    - assets/Runes/p/
    - assets/Runes/q/
    - assets/Runes/r/
    - assets/Runes/s/
    - assets/Runes/t/
    - assets/Runes/u/
    - assets/Runes/v/
    - assets/Runes/w/
    - assets/Runes/x/
    - assets/Runes/y/
    - assets/Runes/z/
    - "assets/themes/Math Night.txt"
    - assets/key/Runes_key.png
    - "assets/themes/Inspirational Quotes.txt"
    - "assets/themes/Fun Facts For Kids.txt"
